simpleviewinc/tap-events-force

.gitignore
package.json
src/assets/icons/evf/elements/dayToggleLeft.js
src/assets/icons/evf/elements/dayToggleRight.js
src/components/button/evfButton.js
src/components/dates/dayToggle.js
src/components/dates/updateDayButton.js
src/components/hocs/withAppHeader.js
src/components/sessions.js
src/containers/gridContainer.js
src/containers/rootContainer.js
src/theme/components/button/evfButton.js
src/theme/components/dates/dayToggle.js
src/theme/components/grid/gridItem.js
src/theme/components/labelButton.js
src/theme/components/labelList.js
src/theme/components/labelTag.js
src/theme/components/modals/baseModal.js
src/theme/components/modals/errorModal.js
src/theme/components/modals/filterModal.js
src/theme/components/modals/groupBookingModal.js
src/theme/components/modals/presenterDetailsModal.js
src/theme/components/sessionLink.js
src/theme/components/sessionTime.js
src/theme/components/sessions.js
src/theme/containers/gridContainer.js
src/theme/dynamicClassMap.js
tap.js

**Ticket [ZEN-355](https://jira.simpleviewtools.com/browse/ZEN-355)** 
> **Notes**
> This PR is directly tied to [this PR](https://github.com/simpleviewinc/keg-hub/pull/38)
>   * They should be merged at the same time
>
> Originally this ticket was to add a `react-helmet`
>   * I could not get that library to not de-dupe styles that were already added
>   * I knew it had to be possible, so I wrote it myself
>
> Because of this, the jira ticket and this pull request don't really line up
>   * This should be the last styling change ticket. At least I hope it is
>   * I'm tired of dealing with it
* Events-Force is defining their styles in CSS
* Their clients can define custom CSS as well
* Currently, the tap, using re-theme, is only compatible with JSON style objects
* We need to be able to …

Zen 355 styles fixes

---

configs/rollup.config.js
package.json
src/components/button/evfButton.js
src/components/dates/dayToggle.js
src/components/modals/presenterDetails.js
src/hooks/useParsedStyle.js
src/theme/components/dates/dayToggle.js
src/theme/components/sessions.js
src/theme/dynamicClassMap.js
src/utils/dateTime/getTimeFromDate.js
src/utils/models/sessions/buildHourSessionsMap.js

* The keg-sessions bundle is larger then it needs to be
* There's a number of things we can do to improve the bundle size
* Improve the keg-sessions packages by reducing the bundle size
* I got bundle size down to around 214kb - This is more then 2x smaller then it was before
* `.gitignore`
* Ignores the fonts folder
* At some point I'm going to update how the fonts are loaded. For local development I want to store the fonts
* This way we don't have to keep calling google for them
* `configs/rollup.config.js`
* Added `terser` and `analyze` roll-up plugin
* terser - Minifies the build. Cuts out about 200kb
* analyze - Give an overview of what's included in the bundle by size
* `package.json`
* Updated the version to be `0.2.0`
* There should be no breaking changes
* All should be backwards …

Keg sessions@0.2.0

---

src/utils/dateTime/getTimeFromDate.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-386)
* With the latest update on `getTimeFromDate` to use the built in `Date` constructor. It introduced a bug on safari where it does not properly create a `Date` object if the formatting is "incorrect"
* we're passing in a string to this helper function and it is formatted like: `2020-08-03 13:00:00`
* safari does not support parsing the dashes `-`. but it does support `/`
* so just replace the dashes with slashes if the parsing fails
* Update `getTimeFromDate` to format the date to an acceptable format for browser that complains about it
* `src/utils/dateTime/getTimeFromDate.js`
* parse the date string for safari / any other browser that doesn't support `-`
* run `keg dpg run …

fixed date parsing for safari

---

src/components/hocs/tapIndex.js
src/components/hocs/withPortal.js
src/components/modals/baseModal.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-389)
* currently, we set the zIndex of the BaseModal to a high value so that it appears above other elements on the dom
* however, if a parent component has defined overflow: hidden or a z-index style, the modal may still appear below the parent on the z-axis.
* this is only relevant on web
* we need BaseModal to always break through
* you can see that the modal is appearing below the nav bar
* ![image](https://user-images.githubusercontent.com/3317835/94968989-c2947400-04b6-11eb-89c5-6457b90b6170.png)
* Utilize ReactDOM.createPortal to render the modals in the body element (ref)[https://reactjs.org/docs/portals.html]
* It will render to the `body` element by default until Evf lets me know of a different location. We can …

Zen 389 portal for web modals

---

src/actions/session/mapSessionInterface.js
src/components/sessions.js
src/utils/models/sessions/__tests__/buildHourSessionsMap.js
src/utils/models/sessions/buildHourSessionsMap.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-390)
* I noticed that our agenda sessions grid isn't actually sorting the sessions by time block. it just so happens that the test data we've been using is in the correct order
* have the `AGENDA_SESSIONS` store actually be sorted by timeblock
- updated unit test for buildHourSessionsMap
- updated buildHrSessionsMap to return an array instead of an object so we can sort it by time block
* run `keg dpg run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:sort-by-hour-block`
* navigate to http://local.kegdev.xyz/
* switch to Day 1
* modify the JSON data to add a new session on day 1, and set the start time > 9 am  && < 1 pm
* something like this
* hit apply
* verify that the new session block gets added in …

Sort agendaSessions by timeblock

---

src/components/modals/filter.js
src/theme/components/modals/filterModal.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-374)
* Filter Modal should contain a `clear filter` button. as shown in the new specs powerpoint here https://docs.google.com/presentation/d/19PRD8-W6hhWZvl8u1IPUOAkdnUJunCQ2zgGntuxM9Wk/edit?ts=5f58932a#slide=id.g8b8266aa53_0_208
* it should:
* only display if any filter has been selected
* on press > clears out currently selected filter. does NOT apply it automatically
* Add this `clear filters` button on the filter modal
* use the already existing action `clearSelectedFilters`
* `src/components/modals/filter.js`
* add the button and attach the action `clearSelectedFilters`
* minor cleanup
* Run `keg dpg run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-374-modal-filter-clear-btn`
* Open the filter …

Zen 374 modal filter clear btn

---

src/utils/models/tickets/getAllBookedTickets.js

* on Safari 11.1, the use of the Array prototype function `flatMap` is not supported
* replace it with `reduce` code that does the same thing without relying on the unsupported function ( and is more efficient, to boot ) 
* Nicole already tested this on Safari 11.1, and it passes.
* but this image is available to verify everything still works as expected (the code runs when the group booking modal opens): `keg evf pack run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:browser-compat-fixes`

replaced use of .flatMap fn with one from jsutils for Safari 11.1 error

---

src/utils/models/attendees/sortAttendeeIntoSections.js
src/utils/models/tickets/getAllBookedTickets.js

* there was a bug with the mapping of the tickets based on the recent change, the sub tickets weren't getting flattened
* fix bug
* `keg evf pack run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:booked-ticket-mapping-fix`
* ensure that the `/test` page and the group booking modal loads, and verify that you see no warnings in the console about not finding a valid ticket (it would say "Could not find a valid ticket for attendee")

fixed bug where booked tickets didnt get flattened

---

src/components/booking/attendeeCheckboxItem.js
src/components/modals/alert.js
src/components/modals/baseModal.js
src/hooks/booking/__tests__/useBookingLists.js
src/mocks/eventsforce/testData.js
src/theme/components/booking/attendeeCheckboxItem.js
src/theme/components/modals/alertModal.js
src/theme/components/modals/baseModal.js
src/theme/components/modals/filterModal.js
src/theme/components/modals/groupBookingModal.js
src/theme/components/modals/presenterDetailsModal.js
src/theme/components/modals/sessionDetailsModal.js

* modal padding was not consistent and each modal was redefining its own padding/margins'
* in group booking modal, very long names that were also on waiting list weren't wrapping
* `useBookingLists` tests were failing
* Make all modal bodies use the same padding, to be consistent and less brittle
* Make long waiting-list names wrap on small screen widths
* Fix `useBookingLists` tests
* `src/components/booking/attendeeCheckboxItem.js`
* updates to get it wrapping
* `src/components/modals/baseModal.js`
* updated to wrap modal children in a view that can define consistent padding in a single place
* `src/hooks/booking/__tests__/useBookingLists.js`
* fixed tests by mocking out `useMemo`, also added a `jest.resetAllMocks()` call after all tests run
* `**/**.js`
* updated all the other modals …

Modal Style Updates + Fixed Tests

---

src/components/dates/dayToggle.js
src/components/modals/filter.js
src/components/sessions.js
src/containers/gridContainer.js
src/theme/components/grid/gridTileContent.js
src/theme/components/sessions.js
src/theme/containers/gridContainer.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-369)
* After sessions are filtered, there should be a way to clear them from the sessions list. Otherwise the user will have to open the filter modal and hit clear filter > apply
* this is a small nice-to-have improvement to save the user a few clicks to clear their filters
* Add a `Clear` button on the session agenda next to the `Filter` button
* This clear button should only appear if there are any active filteres
* clicking this button will clear all active filters and apply it to the agenda sessions
* `src/components/dates/dayToggle.js`
* added specific width for the dayToggle string to transform earlier to the mobile view version
* `src/components/modals/filter.js`
* changed the name to `clear all` because that's what …

Zen 369 clear all

---

src/components/sessionLink/sessionLink.js
src/theme/components/button/evfButton.js
src/theme/components/grid/gridTileContent.js
src/theme/components/sessionLink.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-424)
* Going back over the RegX5 session doc here https://docs.google.com/document/d/1bZIMvNhg6fsU5Tf1edLcoBfpu8rR9qQLGf0Kx-DGMrw/edit#
* minor detailed that was missed is that the link should become underlined when hovered
* Make session link and presenter link underline on hover
* `src/components/sessionLink/sessionLink.js`
* added useThemeHover hook
* added the theme ref to the Text component
* `src/theme/components/sessionLink.js`
* added default and hover state styles
* run `keg dpg run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-424-session-link-underline`
* verify that the Session link and presenter link is underlined when you hover them 
* …

Zen 424 session link underline

---

src/components/grid/gridTileContent.js
src/components/sessionLink/sessionLink.js
src/mocks/eventsforce/testData.js
src/theme/components/grid/gridItem.js
src/theme/components/grid/gridTileContent.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-425)
* Each grid item has a dynamic height and minHeight of 294px (from mockup)
* The grid item(s) in each block container (IF they are on the same row) should have the same height
* it should not do this
* ![image](https://user-images.githubusercontent.com/3317835/97214150-e11d2080-177f-11eb-9854-37a6ee9738d1.png)
* Update styling on the grid item and gridTileContent so that the height of each item grows accordingly
- `src/mocks/eventsforce/testData.js`
- updated mockdata with more presenters
- `src/components/sessionLink/sessionLink.js`
- added className to sessionLink, so we can override it for presenter name classname
- `src/theme/components/grid/gridTileContent.js`
- wrapped presenterNames in a container so it can be …

GridItem Height fix

---

src/hooks/booking/useBookingLists.js
src/hooks/booking/useRestrictedAttendeeIds.js

**Ticket**: [ZEN-428](https://jira.simpleviewtools.com/browse/ZEN-428)
* There's a bug causing restricted attendees to be preselected in the groupbooking modal
* Ensure restricted attendees are never pre-selected
* `src/hooks/booking/useBookingLists.js`
* fixed call to `isBookable`, which was erroneously being passed an attendee object, rather than its id. 
* `src/hooks/booking/useRestrictedAttendeeIds.js`
* did some refactoring, and added a validate call to help prevent this error in the future
* `keg evf pack run package=docker.pkg.github.com/simpleviewinc/keg-packages/tap:zen-428-preselecting-bug`
* navigate to `Day 2` on `local.kegdev.xyz`
* scroll to the bottom, and press the `Select` button on the last session (`Session on day 2 Demo 3`)
* ensure everybody **except** `Mrs. …

Zen 428 preselecting bug

---

src/components/labels/labelTag.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-447)
`[semver]: patch`
* related to https://github.com/simpleviewinc/keg-hub/pull/66
* i noticed the className wasn't setup properly for labelTag
* fix it
* `src/components/labels/labelTag.js`
* should be an array of strings
* testing covered in https://github.com/simpleviewinc/keg-hub/pull/66

fixed className for labelTag

---

src/components/booking/attendeeBookingList.js
src/components/booking/groupBooker.js
src/hooks/booking/__tests__/useBookingLists.js
src/hooks/booking/useBookingLists.js
src/hooks/booking/useBookingState.js
src/hooks/booking/useBookingTimeConflicts.js
src/hooks/booking/useGroupCounts.js
src/hooks/booking/useInitGroupBooking.js
src/hooks/models/attendees/index.js
src/hooks/models/attendees/useIsAttendeeDisabledCallback.js
src/hooks/models/index.js
src/mocks/eventsforce/bookingStates/conflict.js
src/mocks/eventsforce/bookingStates/index.js

**Ticket**: [ZEN-427](https://jira.simpleviewtools.com/browse/ZEN-427)
and [ZEN-458](https://jira.simpleviewtools.com/browse/ZEN-458)
* currently, the group booking modal does not disable attendee checkbox items if those attendees have a time conflict between the selected session and another session
* update the group booking modal to ensure that attendees with time-conflicts are disabled and greyed-out
* `src/components/booking/attendeeBookingList.js`
* updated to disable attendees checkbox items if they have a time conflict
* `src/hooks/booking/useBookingLists.js`
* updated to ensure that attendees with time-conflicts are never pre-selected by the group booking modal
* `src/hooks/models/attendees/useIsAttendeeDisabledCallback.js`
* created a more general hook, …

Zen 427 group time conflicts

---

src/assets/icons/evf/elements/filter.js
src/theme/components/grid/gridItem.js
src/theme/components/labelList.js
src/theme/components/modals/filterModal.js
src/theme/components/sessionTime.js
src/theme/components/sessions.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-459)
* there appears to be a breaking change when upgrading to react-native-web 14.x regarding `flexBasis`
* this caused the gridItem flexBasis to not get applied properly
- fixed a bug with filter icon sizing
- fixed gridItem flexBasis width
* `src/assets/icons/evf/elements/filter.js`
* removed default values from filter icon svg, we just set the height in the styles
* there was an issue where the icon size was too small when the default values was there
* `src/theme/components/grid/gridItem.js`
* set the flexBasis values in the `flex`key
* `src/theme/components/labelList.js`
* uneeded style removed
* `src/theme/components/modals/filterModal.js`
* uneeded style removed
* run `keg evf pack run …

grid item bug fix

---

apps/Main.js
apps/Sessions.js
index.js
src/theme/tapIndex.js

[Semver-Status] patch
> This PR should be reviewed along with [this PR](https://github.com/simpleviewinc/keg-hub/pull/72)
* Currently there is no way to overwrite the default theme config
* Keg-Components has been updated to allow dynamically setting the Theme
* This allows overwriting the default theme config
* Should allow overwriting the default theme config
* `apps/Main.js` && `apps/Sessions.js`
* Moved call to setDefaultTheme to theme file
* Removed `setRNPlatform` call. It's no longer needed
* `src/theme/tapIndex.js`
* Updated to call theme initialize function
* Run the docker package => `keg evf pack run docker.pkg.github.com/simpleviewinc/keg-packages/tap:keg-theme-as-functions`
* Navigate to this URL => http://evf-keg-theme-as-functions.local.kegdev.xyz/
* Ensure everything looks …

Theme As Functions

---

apps/Sessions.js
configs/rollup.config.js
src/theme/components/button/evfButton.js

**Ticket**: [ZEN-456](https://jira.simpleviewtools.com/browse/ZEN-456)
[Semver-Status] patch
> ### Notes
> * This pr is dependent on two other PR's
>   * [keg-consumer](https://github.com/simpleviewinc/keg-test-consumer/pull/10)
>   * [keg-hub](https://github.com/simpleviewinc/keg-hub/pull/88)
> * Those PRs should be reviewed along with this one
> * There something wrong with how the theme's `tapIndex` file is being imported
>   * This needs to be investigated further at some point
> * I turned off mangling in terser. This should only be a temporary work around
>   * This needs to be investigated further at some point
* There's some issue with recent changes that were causing the rollup export to fail
* Fix the rollup export so it can be consumed by an external app 
* `apps/Sessions.js`
* …

Fix Rollup Export

---

src/components/button/bookingButton.js
src/mocks/eventsforce/bookingStates/conflict.js
src/utils/models/sessions/__tests__/getDisabled.js
src/utils/models/sessions/bookingStateFactory.js
src/utils/models/sessions/getDisabled.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-458)
* in group booking mode, when every single person is booked to a session. Any adjacent session should have its booking button disabled. Just like the single booking mode
* group booking conflict - unlimited is an edge case that was missed
* exctract out `getDisabled` method so it can be unit tested
* `src/mocks/eventsforce/bookingStates/conflict.js`
* updated conflict test data
* `src/utils/models/sessions/bookingStateFactory.js`
* extracted `getDisabled` to its own file
* `src/utils/models/sessions/getDisabled.js`
* the extracted method from `bookingStateFactory`
*  minor adjust so it will disable when capacity is unlimited && conflict exists
* run `keg evf pack run …

Zen 458 group booking disable

---

container/Dockerfile
container/docker-compose.yml
container/mutagen.yml
container/run.sh
container/values.yml

* The keg-cli can use a container folder for taps as injected apps
* This decouples the tap from the keg-cli, while at the same time still allows it to be used
* Add a container folder
* ensure it still build and runs as expected
* Copied the `containers/tap` folder from the Keg-CLI into the root dir
* Made some minor path updates for the container folder
**Test 1**
* Pull this PR => `keg evf && keg pr 113`
* Remove any existing `tap || evf` docker images. This ensures a fresh build
* Run the cmd `keg evf start` - This should build and start the events-force tap, using the container folder
* Ensure everything runs as expected
**Test 2**
*  Next run the command `docker inspect evf`
* This should print out a bunch of data about the events-force docker image 
* In the output, search for the …

feat: Add container folder

---

src/components/sessionsHeader/sessionsHeader.js
src/components/sessionsList/sessionsList.js
src/hooks/models/useAgenda.js
src/mocks/eventsforce/testData.js
src/models/agendaDay.js
src/theme/components/dates/dayToggle.js
src/utils/models/agenda/agendaDays/getDayName.js
src/utils/models/agenda/agendaDays/index.js

**Ticket**: [issue_id](https://jira.simpleviewtools.com/browse/ZEN-541)
* EVF changed the behavior of the dayToggle again. there must be no calculated rendering of the day date. It must come directly from the dayName json value for each day.
- add prop dayName to agendaDay
- use agendaDay.dayName as the label header instead of calculating it
* `src/components/sessionsList/sessionsList.js`
* update to not calculate dayName but instead use the JSON value
* updated the `AgendaDay` model and style slightly
* run `keg evf pack run evf:zen-541-dayname-label`
* navigate to http://evf-zen-541-dayname-label.local.kegdev.xyz/
* Open the JSON editor
* Update the `dayName` properties
* [image](https://user-images.githubusercontent.com/3317835/107407890-79d57300-6ac7-11eb-8895-5274723bd82a.png)
* hit …

ZEN-541 Day Name Text

---

container/Dockerfile
container/values.yml

**Ticket**: [ZEN-543](https://jira.simpleviewtools.com/browse/ZEN-543)
* As part of ZEN-543, we determined we should change the default docker image tag from "master" to "develop" for clarity and consistency with the git branches
* Update all references of the old "master" to "develop"
* Ensure building images uses "develop"
* `container/Dockerfile`
* updated keg base image to be `tap:develop`
* `container/values.yml`
* updated tag to "develop"
* follow the "setup" section in the testing notes here: https://github.com/simpleviewinc/keg-cli/pull/59
* you don't have to delete all images, though, just `evf`
* `keg evf build`
* verify it is tagged with "develop"

ZEN-543: Develop Tag

---

container/docker-compose.yml
container/run.sh
container/values.yml
package.json

**Ticket**: [ZEN-609](https://jira.simpleviewtools.com/browse/ZEN-609)
* This PR should be reviewed along side [this keg-cli pr](https://github.com/simpleviewinc/keg-cli/pull/61)
* When we run our docker packages on the staging server, there are a number of features that we don't need, like running in development modes
* These features slow down the execution, and in some cases prevent resolving the application url
* Automate bundling the application when the docker image is created
* This will allow the staging server serve the bundle instead of using the development server
* `container/docker-compose.yml`
* Added `DOC_BUILD_PATH` env
* `container/run.sh`
* Updated to run a command based on `NODE_ENV`
* Allows running the bundled app in non-development environments
* …

Bundle Automation

---

src/components/booking/attendeeCheckboxItem.js
src/components/booking/attendeeCheckboxLabel.js
src/components/booking/groupBooker.js
src/components/booking/waitingItem.js
src/components/checkbox/evfCheckbox.js
src/components/form/index.js
src/components/form/label/index.js
src/components/form/label/label.native.js
src/components/form/label/label.web.js
src/components/tapIndex.js
src/theme/components/booking/attendeeCheckboxItem.js
src/theme/components/modals/groupBookingModal.js

**Ticket**: [ZEN-649](https://jira.simpleviewtools.com/browse/ZEN-649)
* Use a label with the attendee checkbox item and link it to the input element, to improve accessibility
* `src/components/booking/attendeeCheckboxItem.js`
* updated the `id` to be more clear
* extracted the label component to a separate file
* `src/components/booking/attendeeCheckboxLabel.js`
* this is the extracted label component
* updated it to use a `label` instead of `Text` (on web)
* it now handles both the waiting and non-waiting state 
* refactored it to use styled components (where possible -- to do more, we need to update `reStyle` to support size keys)
* `src/components/booking/groupBooker.js`
* this is just removing the modified asterisk that they requested we remove. It's technically handled by another …

ZEN-649: Checkbox Accessibility Updates

---

package.json
src/components/sessionsList/sessionsList.js

**Ticket**: [ZEN-663](https://jira.simpleviewtools.com/browse/zen-663)
* Fix the infinite iframe-resizing bug for EventsForce
* `src/components/sessionsList/sessionsList.js`
* updated `marginBottom` of sessions list to be computed only once when we detect that we are inside of an iframe, otherwise it behaves the same
* `keg consumer pack run --package consumer:zen-663-resizer`
* this starts up the keg-test-consumer with this branch of tap-events-force synced-in
* it also configures it with the iframe-resizer plugin
* open it in your browser: http://consumer-zen-663-resizer.local.keghub.io
* Verify that the sessions list looks and behaves normal
* Next, run `keg && cd external && git clone https://github.com/simpleviewinc/iframe-tester-evf && cd iframe-tester-evf`
* `yarn install`
* …

ZEN-663 iFrame Hotfix

---

.github/workflows/checkOutdated.yml

* The dev team has agreed that no PR should be reviewed or QA-tested unless it is up to date with the `develop`
* This github action should automatically check that
* We only need to check for a green check-mark when a PR is opened
* Verify the action ran on this PR and succeeded:
* We should gradually add this action to any repo we work on

Add new action to reject outdated PRs

---

src/components/__tests__/bookingButton.integration.js
src/components/__tests__/dayToggle.integration.js
src/components/__tests__/filterModal.integration.js
src/components/__tests__/groupBooker.integration.js
src/components/__tests__/sessions.integration.js
src/components/booking/attendeeCheckboxItem.js
src/components/booking/attendeeCheckboxLabel.js
src/components/button/evfButton.js
src/components/checkbox/evfCheckbox.js
src/components/form/label/label.web.js
src/contexts/booking/groupBookingReducer.js
src/mocks/eventsforce/bookingStates/onWaitingList.js
src/mocks/eventsforce/evfModalBuilder.js
src/mocks/eventsforce/testData.js
src/models/attendee.js
types/efSessionAgenda.ts
types/exampleSessionData.ts

> Note: I will be branching off of this for ZEN-669, so please do not postpone review
* As I was working on `ZEN-669`, I noticed that we had actually broken the group booking modal in recent commits on develop.
* Furthermore, the group booker lacked any integration tests, so I wanted to correct that
* `src/components/__tests__/groupBooker.integration.js`
* Add some integration tests for the group booker. This is by no means exhaustive, but it's a good start.
* `src/components/booking/attendeeCheckboxItem.js`
* Fix the bug in which the event handler for checkbox-click was not being passed the attendee id but rather the DOM element's id, which had additional text in it.
* Wrapped the component in a `View` to that I could add some accessibility metadata
* …

Group Modal Fixes and Tests
